// Gran Turismo 7 car lists — sourced exclusively from the official GT7 car list
// https://www.gran-turismo.com/us/gt7/carlist/ (574 cars total, as of August 2026)

export const GT7_GR1 = [
  "Alpine Vision Gran Turismo 2017",
  "Audi R18 '16",
  "Audi R18 TDI '11",
  "Audi Vision Gran Turismo",
  "BMW M Hybrid V8 '25",
  "Bugatti Vision Gran Turismo (Gr.1)",
  "Dodge SRT Tomahawk Vision Gran Turismo (Gr.1)",
  "Ferrari 499P '23",
  "Genesis X Gran Racer Vision Gran Turismo Concept",
  "HYUNDAI N 2025 Vision Gran Turismo (Gr.1)",
  "Jaguar XJR-9 '88",
  "Mazda 787B '91",
  "Mazda LM55 Vision Gran Turismo (Gr.1)",
  "McLaren Ultimate Vision Gran Turismo (Gr.1)",
  "Nissan GT-R LM NISMO '15",
  "Nissan R92CP '92",
  "Peugeot 908 HDi FAP '10",
  "Peugeot 9X8 '25",
  "Peugeot L750R HYbrid Vision Gran Turismo, 2017",
  "Porsche 919 Hybrid '16",
  "Porsche 962 C '88",
  "Porsche 963 '24",
  "Sauber Mercedes C9 '89",
  "TOYOTA GR010 HYBRID '21",
  "Toyota TS030 Hybrid '12",
  "Toyota TS050 - Hybrid '16"
];

export const GT7_GR2 = [
  "Audi RS 5 Turbo DTM '19",
  "BMW McLaren F1 GTR Race Car '97",
  "Honda NSX CONCEPT-GT '16",
  "Honda NSX GT500 '08",
  "Lexus RC F GT500 '16",
  "Lexus SC430 GT500 '08",
  "Mercedes-Benz CLK-LM '98",
  "Nissan GT-R GT500 '08",
  "Nissan GT-R NISMO GT500 '16",
  "Toyota GT-One (TS020) '99"
];

export const GT7_GR3 = [
  "Alfa Romeo 4C Gr.3",
  "Aston Martin DBR9 GT1 '10",
  "Aston Martin V12 Vantage GT3 '12",
  "Audi R8 LMS '15",
  "Audi R8 LMS Evo '19",
  "BMW M3 GT '11",
  "BMW M6 GT3 Endurance Model '16",
  "BMW M6 GT3 Sprint Model '16",
  "BMW Z4 GT3 '11",
  "Chevrolet Corvette C7 Gr.3",
  "Dodge Viper SRT GT3-R '15",
  "Ferrari 296 GT3 '23",
  "Ferrari 458 Italia GT3 '13",
  "Ford GT LM Race Car Spec II",
  "Ford GT LM Spec II Test Car",
  "Ford GT Race Car '18",
  "Ford Mustang Gr.3",
  "Genesis X GR3",
  "GT by Citroën Race Car (Gr.3)",
  "Honda NSX Gr.3",
  "Honda NSX GT500 '00",
  "Hyundai Genesis Gr.3",
  "Jaguar F-type Gr.3",
  "Lamborghini Huracán GT3 '15",
  "Lexus RC F GT3 '17",
  "Lexus RC F GT3 prototype '16",
  "MAZDA RX-VISION GT3 CONCEPT",
  "Mazda Atenza Gr.3",
  "McLaren 650S GT3 '15",
  "McLaren F1 GTR - BMW '95",
  "Mercedes-AMG GT3 '16",
  "Mercedes-AMG GT3 '20",
  "Mercedes-Benz SLS AMG GT3 '11",
  "Mitsubishi Lancer Evolution Final Edition Gr.3",
  "Nissan GT-R GT500 '99",
  "Nissan GT-R NISMO GT3 '13",
  "Nissan GT-R NISMO GT3 '18",
  "Nissan Skyline Super Silhouette Group 5 '84",
  "PEUGEOT Vision Gran Turismo (Gr.3)",
  "Peugeot RCZ Gr.3",
  "Porsche 911 GT3 R (992) '22",
  "Porsche 911 RSR (991) '17",
  "Renault Sport R.S.01 GT3 '16",
  "Subaru BRZ GT300 '21",
  "Subaru WRX Gr.3",
  "SUZUKI Vision Gran Turismo (Gr.3 Version)",
  "Toyota FT-1 Vision Gran Turismo (Gr.3)",
  "Toyota GR Supra Racing Concept '18",
  "Toyota Supra GT500 '97",
  "Volkswagen Beetle Gr.3",
  "Volkswagen GTI Vision Gran Turismo (Gr.3)"
];

export const GT7_GR4 = [
  "Alfa Romeo 155 2.5 V6 TI '93",
  "Alfa Romeo 4C Gr.4",
  "Aston Martin Vantage Gr.4",
  "Audi TT Cup '16",
  "BMW M4 Gr.4",
  "Bugatti Veyron Gr.4",
  "Chevrolet Corvette C7 Gr.4",
  "Dodge Viper Gr.4",
  "Ferrari 458 Italia Gr.4",
  "Ford Mustang Gr.4",
  "Genesis G70 GR4",
  "GT by Citroën Gr.4",
  "Honda NSX Gr.4",
  "Hyundai ELANTRA N TC '24",
  "Hyundai Genesis Gr.4",
  "Jaguar F-type Gr.4",
  "Lamborghini Huracán Gr.4",
  "Lexus RC F Gr.4",
  "MAZDA3 Gr.4",
  "Mazda Atenza Gr.4",
  "McLaren 650S Gr.4",
  "Mercedes-Benz SLS AMG Gr.4",
  "Mitsubishi Lancer Evolution Final Edition Gr.4",
  "Nissan GT-R Gr.4",
  "Nissan Silvia spec-R Aero (S15) Touring Car",
  "Peugeot RCZ Gr.4",
  "Porsche Cayman GT4 Clubsport '16",
  "Renault Sport Mégane Gr.4",
  "Renault Sport Mégane Trophy '11",
  "Subaru WRX Gr.4",
  "Suzuki Swift Sport KATANA Edition Gr.4",
  "TOYOTA 86 Gr.4",
  "Toyota GR Supra Race Car '19",
  "Volkswagen Scirocco Gr.4"
];

export const GT7_GRB = [
  "Audi Sport quattro S1 Pikes Peak '87",
  "Ford Focus Gr.B Rally Car",
  "Ford Mustang Gr.B Rally Car",
  "Honda NSX Gr.B Rally Car",
  "Hyundai Genesis Gr.B Rally Car",
  "Lancia Delta HF Integrale Rally Car '92",
  "Mitsubishi Lancer Evolution Final Edition Gr.B Rally Car",
  "Nissan GT-R Gr.B Rally Car",
  "Peugeot 205 Turbo 16 Evolution 2 '86",
  "Peugeot RCZ Gr.B Rally Car",
  "Subaru Impreza Rally Car '98",
  "Subaru WRX Gr.B Rally Car",
  "TOYOTA 86 Gr.B Rally Car",
  "Toyota Celica GT-FOUR Rally Car (ST205) '95"
];

export const GT7_GRX = [
  "AFEELA 1 '26",
  "AFEELA Prototype 2024",
  "Alfa Romeo GIULIA TZ2 carrozzata da ZAGATO '65",
  "Alpine A220 Race Car '68",
  "Alpine Vision Gran Turismo",
  "Alpine Vision Gran Turismo Race Mode",
  "Aston Martin DB3S '53",
  "Aston Martin DP-100 Vision Gran Turismo",
  "Audi e-tron Vision Gran Turismo",
  "BMW M4 Safety Car",
  "BMW Vision Gran Turismo",
  "BMW i3 '15",
  "BVLGARI Aluminium Vision Gran Turismo",
  "Bugatti Vision Gran Turismo",
  "Chaparral 2J '70",
  "Chevrolet Chaparral 2X Vision Gran Turismo",
  "Chevrolet Corvette CX Concept '25",
  "Chevrolet Corvette CX.R Vision Gran Turismo Concept",
  "Chevrolet Corvette Stingray Racer Concept '59",
  "DAIHATSU COPEN RJ Vision Gran Turismo",
  "Dallara SF19 Super Formula / Honda '19",
  "Dallara SF19 Super Formula / Toyota '19",
  "Dallara SF23 Super Formula/Honda '23",
  "Dallara SF23 Super Formula/Toyota '23",
  "Dodge Charger SRT Hellcat Safety Car",
  "Dodge SRT Tomahawk GTS-R Vision Gran Turismo",
  "Dodge SRT Tomahawk S Vision Gran Turismo",
  "Dodge SRT Tomahawk X Vision Gran Turismo",
  "Ferrari 250 GTO '62",
  "Ferrari 330 P4 '67",
  "Ferrari Vision Gran Turismo",
  "Ford Mark IV Race Car '67",
  "Genesis X Gran Berlinetta Vision Gran Turismo Concept",
  "Gran Turismo F1500T-A",
  "Gran Turismo F3500-A",
  "Gran Turismo F3500-B",
  "Gran Turismo Racing Kart 125 Shifter",
  "Gran Turismo Red Bull X2014 Junior",
  "Gran Turismo Red Bull X2014 Standard",
  "Gran Turismo Red Bull X2019 Competition",
  "Honda Project 2&4 powered by RC213V",
  "Honda RA272 '65",
  "Honda Sports Vision Gran Turismo",
  "HYUNDAI N 2025 Vision Gran Turismo",
  "INFINITI CONCEPT Vision Gran Turismo",
  "IsoRivolta Zagato Vision Gran Turismo",
  "Italdesign EXENEO Vision Gran Turismo Off-road Mode",
  "Italdesign EXENEO Vision Gran Turismo Street Mode",
  "Jaguar D-type '54",
  "Jaguar Vision Gran Turismo Coupé",
  "Jaguar Vision Gran Turismo Roadster",
  "Jaguar Vision Gran Turismo SV",
  "Jaguar XJ13 '66",
  "Lambo V12 Vision Gran Turismo",
  "LEXUS LF-LC GT Vision Gran Turismo",
  "MINI Clubman Vision Gran Turismo",
  "Maserati A6GCS/53 Spyder '54",
  "Mazda LM55 Vision Gran Turismo",
  "McLaren MP4/4 '88",
  "McLaren Ultimate Vision Gran Turismo",
  "Mercedes-AMG GT Safety Car",
  "Mercedes-Benz 300 SEL 6.8 AMG '71",
  "Mercedes-Benz 300 SL (W194) '52",
  "Mercedes-Benz AMG Vision Gran Turismo",
  "Mercedes-Benz AMG Vision Gran Turismo Racing Series",
  "Mercedes-Benz W 196 R '55",
  "Mitsubishi Concept XR-PHEV EVOLUTION Vision Gran Turismo",
  "NISSAN CONCEPT 2020 Vision Gran Turismo",
  "Nissan GT-R Safety Car",
  "Opel Corsa GSE Vision Gran Turismo",
  "Pagani Zonda R '09",
  "PEUGEOT Vision Gran Turismo",
  "Peugeot L500R HYbrid Vision Gran Turismo, 2017",
  "Polestar 5 Performance '26",
  "Porsche 911 Turbo S Safety Car (992)",
  "Porsche 917 LIVING LEGEND",
  "Porsche 917K '70",
  "Porsche Carrera GTS (904) '64",
  "Porsche Mission X '23",
  "Porsche Spyder type 550/1500RS '55",
  "Porsche Taycan Turbo S '19",
  "Porsche Vision Gran Turismo",
  "Porsche Vision Gran Turismo Spyder",
  "Renault Espace F1 '95",
  "Renault R8 Gordini '66",
  "Renault Sport Mégane R.S. Trophy Safety Car",
  "Renault Sport R.S.01 '16",
  "Shelby Cobra Daytona Coupe '64",
  "SUBARU VIZIV GT Vision Gran Turismo",
  "SUZUKI Vision Gran Turismo",
  "Subaru BRZ Drift Car '17",
  "Subaru WRX STI Isle of Man Time Attack Car '16",
  "Suzuki V6 Escudo Pikes Peak Special '98",
  "Tesla Model 3 Performance '23",
  "Tesla Model S Signature Performance '12",
  "Toyota Ambulance Himedic '21",
  "Toyota Crown Athlete G Safety Car",
  "Toyota FT-1",
  "Toyota FT-1 Vision Gran Turismo",
  "Volkswagen GTI Roadster Vision Gran Turismo",
  "Volkswagen GTI Supersport Vision Gran Turismo",
  "Volkswagen ID.R '19",
  "Xiaomi SU7 Ultra '25",
  "Yangwang U9 '24",
  "Škoda Vision Gran Turismo"
];